#!/bin/bash
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "❌ You are on branch '$branch'. Direct commits are blocked."
  echo "👉 Please create a new branch (git checkout -b feature/my-feature)"
  exit 1
fi